// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

#include "sample.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace com {
namespace mycorp {
namespace mynamespace {
class SampleRecordDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SampleRecord> _instance;
} _SampleRecord_default_instance_;
}  // namespace mynamespace
}  // namespace mycorp
}  // namespace com
static void InitDefaultsscc_info_SampleRecord_sample_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::com::mycorp::mynamespace::_SampleRecord_default_instance_;
    new (ptr) ::com::mycorp::mynamespace::SampleRecord();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::com::mycorp::mynamespace::SampleRecord::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SampleRecord_sample_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_SampleRecord_sample_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_sample_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_sample_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_sample_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_sample_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::mycorp::mynamespace::SampleRecord, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::com::mycorp::mynamespace::SampleRecord, my_field1_),
  PROTOBUF_FIELD_OFFSET(::com::mycorp::mynamespace::SampleRecord, my_field2_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::com::mycorp::mynamespace::SampleRecord)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::com::mycorp::mynamespace::_SampleRecord_default_instance_),
};

const char descriptor_table_protodef_sample_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014sample.proto\022\026com.mycorp.mynamespace\"4"
  "\n\014SampleRecord\022\021\n\tmy_field1\030\001 \001(\005\022\021\n\tmy_"
  "field2\030\002 \001(\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_sample_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_sample_2eproto_sccs[1] = {
  &scc_info_SampleRecord_sample_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_sample_2eproto_once;
static bool descriptor_table_sample_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sample_2eproto = {
  &descriptor_table_sample_2eproto_initialized, descriptor_table_protodef_sample_2eproto, "sample.proto", 100,
  &descriptor_table_sample_2eproto_once, descriptor_table_sample_2eproto_sccs, descriptor_table_sample_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_sample_2eproto::offsets,
  file_level_metadata_sample_2eproto, 1, file_level_enum_descriptors_sample_2eproto, file_level_service_descriptors_sample_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_sample_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_sample_2eproto), true);
namespace com {
namespace mycorp {
namespace mynamespace {

// ===================================================================

void SampleRecord::InitAsDefaultInstance() {
}
class SampleRecord::_Internal {
 public:
};

SampleRecord::SampleRecord()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.mycorp.mynamespace.SampleRecord)
}
SampleRecord::SampleRecord(const SampleRecord& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&my_field2_, &from.my_field2_,
    static_cast<size_t>(reinterpret_cast<char*>(&my_field1_) -
    reinterpret_cast<char*>(&my_field2_)) + sizeof(my_field1_));
  // @@protoc_insertion_point(copy_constructor:com.mycorp.mynamespace.SampleRecord)
}

void SampleRecord::SharedCtor() {
  ::memset(&my_field2_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&my_field1_) -
      reinterpret_cast<char*>(&my_field2_)) + sizeof(my_field1_));
}

SampleRecord::~SampleRecord() {
  // @@protoc_insertion_point(destructor:com.mycorp.mynamespace.SampleRecord)
  SharedDtor();
}

void SampleRecord::SharedDtor() {
}

void SampleRecord::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SampleRecord& SampleRecord::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SampleRecord_sample_2eproto.base);
  return *internal_default_instance();
}


void SampleRecord::Clear() {
// @@protoc_insertion_point(message_clear_start:com.mycorp.mynamespace.SampleRecord)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&my_field2_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&my_field1_) -
      reinterpret_cast<char*>(&my_field2_)) + sizeof(my_field1_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* SampleRecord::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 my_field1 = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          my_field1_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double my_field2 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17)) {
          my_field2_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool SampleRecord::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:com.mycorp.mynamespace.SampleRecord)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 my_field1 = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (8 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32>(
                 input, &my_field1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double my_field2 = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (17 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   double, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &my_field2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.mycorp.mynamespace.SampleRecord)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.mycorp.mynamespace.SampleRecord)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void SampleRecord::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.mycorp.mynamespace.SampleRecord)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 my_field1 = 1;
  if (this->my_field1() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32(1, this->my_field1(), output);
  }

  // double my_field2 = 2;
  if (!(this->my_field2() <= 0 && this->my_field2() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDouble(2, this->my_field2(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:com.mycorp.mynamespace.SampleRecord)
}

::PROTOBUF_NAMESPACE_ID::uint8* SampleRecord::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.mycorp.mynamespace.SampleRecord)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 my_field1 = 1;
  if (this->my_field1() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->my_field1(), target);
  }

  // double my_field2 = 2;
  if (!(this->my_field2() <= 0 && this->my_field2() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(2, this->my_field2(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.mycorp.mynamespace.SampleRecord)
  return target;
}

size_t SampleRecord::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.mycorp.mynamespace.SampleRecord)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double my_field2 = 2;
  if (!(this->my_field2() <= 0 && this->my_field2() >= 0)) {
    total_size += 1 + 8;
  }

  // int32 my_field1 = 1;
  if (this->my_field1() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->my_field1());
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SampleRecord::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.mycorp.mynamespace.SampleRecord)
  GOOGLE_DCHECK_NE(&from, this);
  const SampleRecord* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SampleRecord>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.mycorp.mynamespace.SampleRecord)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.mycorp.mynamespace.SampleRecord)
    MergeFrom(*source);
  }
}

void SampleRecord::MergeFrom(const SampleRecord& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.mycorp.mynamespace.SampleRecord)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.my_field2() <= 0 && from.my_field2() >= 0)) {
    set_my_field2(from.my_field2());
  }
  if (from.my_field1() != 0) {
    set_my_field1(from.my_field1());
  }
}

void SampleRecord::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.mycorp.mynamespace.SampleRecord)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SampleRecord::CopyFrom(const SampleRecord& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.mycorp.mynamespace.SampleRecord)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SampleRecord::IsInitialized() const {
  return true;
}

void SampleRecord::InternalSwap(SampleRecord* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(my_field2_, other->my_field2_);
  swap(my_field1_, other->my_field1_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SampleRecord::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace mynamespace
}  // namespace mycorp
}  // namespace com
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::com::mycorp::mynamespace::SampleRecord* Arena::CreateMaybeMessage< ::com::mycorp::mynamespace::SampleRecord >(Arena* arena) {
  return Arena::CreateInternal< ::com::mycorp::mynamespace::SampleRecord >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
