/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sample.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sample.pb-c.h"
void   com__mycorp__mynamespace__sample_record__init
                     (Com__Mycorp__Mynamespace__SampleRecord         *message)
{
  static const Com__Mycorp__Mynamespace__SampleRecord init_value = COM__MYCORP__MYNAMESPACE__SAMPLE_RECORD__INIT;
  *message = init_value;
}
size_t com__mycorp__mynamespace__sample_record__get_packed_size
                     (const Com__Mycorp__Mynamespace__SampleRecord *message)
{
  assert(message->base.descriptor == &com__mycorp__mynamespace__sample_record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__mycorp__mynamespace__sample_record__pack
                     (const Com__Mycorp__Mynamespace__SampleRecord *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__mycorp__mynamespace__sample_record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__mycorp__mynamespace__sample_record__pack_to_buffer
                     (const Com__Mycorp__Mynamespace__SampleRecord *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__mycorp__mynamespace__sample_record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Mycorp__Mynamespace__SampleRecord *
       com__mycorp__mynamespace__sample_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Mycorp__Mynamespace__SampleRecord *)
     protobuf_c_message_unpack (&com__mycorp__mynamespace__sample_record__descriptor,
                                allocator, len, data);
}
void   com__mycorp__mynamespace__sample_record__free_unpacked
                     (Com__Mycorp__Mynamespace__SampleRecord *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__mycorp__mynamespace__sample_record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__mycorp__mynamespace__sample_record__field_descriptors[2] =
{
  {
    "my_field1",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Com__Mycorp__Mynamespace__SampleRecord, my_field1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "my_field2",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Com__Mycorp__Mynamespace__SampleRecord, my_field2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__mycorp__mynamespace__sample_record__field_indices_by_name[] = {
  0,   /* field[0] = my_field1 */
  1,   /* field[1] = my_field2 */
};
static const ProtobufCIntRange com__mycorp__mynamespace__sample_record__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor com__mycorp__mynamespace__sample_record__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.mycorp.mynamespace.SampleRecord",
  "SampleRecord",
  "Com__Mycorp__Mynamespace__SampleRecord",
  "com.mycorp.mynamespace",
  sizeof(Com__Mycorp__Mynamespace__SampleRecord),
  2,
  com__mycorp__mynamespace__sample_record__field_descriptors,
  com__mycorp__mynamespace__sample_record__field_indices_by_name,
  1,  com__mycorp__mynamespace__sample_record__number_ranges,
  (ProtobufCMessageInit) com__mycorp__mynamespace__sample_record__init,
  NULL,NULL,NULL    /* reserved[123] */
};
